/*
NuoDB Control Plane REST API

NuoDB Control Plane (CP) allows users to create and manage NuoDB databases remotely using a Database as a Service (DBaaS) model.

API version: 2.3.0
Contact: NuoDB.Support@3ds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nuodbaas

import (
	"encoding/json"
	"fmt"
)

// IntOrString - struct for IntOrString
type IntOrString struct {
	Int32 *int32
	String *string
}

// int32AsIntOrString is a convenience function that returns int32 wrapped in IntOrString
func Int32AsIntOrString(v *int32) IntOrString {
	return IntOrString{
		Int32: v,
	}
}

// stringAsIntOrString is a convenience function that returns string wrapped in IntOrString
func StringAsIntOrString(v *string) IntOrString {
	return IntOrString{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *IntOrString) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(IntOrString)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(IntOrString)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IntOrString) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IntOrString) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableIntOrString struct {
	value *IntOrString
	isSet bool
}

func (v NullableIntOrString) Get() *IntOrString {
	return v.value
}

func (v *NullableIntOrString) Set(val *IntOrString) {
	v.value = val
	v.isSet = true
}

func (v NullableIntOrString) IsSet() bool {
	return v.isSet
}

func (v *NullableIntOrString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntOrString(val *IntOrString) *NullableIntOrString {
	return &NullableIntOrString{value: val, isSet: true}
}

func (v NullableIntOrString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntOrString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


