version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - predeclared
    #- staticcheck  # Generates lots of useless warnings
    - unconvert
    - unparam
    - unused
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nuodb/terraform-provider-nuodbaas
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
