# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - predeclared
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - vet

linters-settings:
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/nuodb/terraform-provider-nuodbaas
  nolintlint:
    require-explanation: true
    require-specific: true
