provider:
  name: nuodbaas
resources:
  project:
    create:
      path: /projects/{organization}/{project}
      method: PUT
    read:
      path: /projects/{organization}/{project}
      method: GET
    schema:
      attributes:
        aliases:
          project: name
