apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: minimal-resources
spec:
  values:
    admin:
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 500Mi
        requests:
          cpu: 250m
          memory: 500Mi
      persistence:
        enabled: true
        size: 1Gi
    database:
      sm:
        hotCopy:
          enablePod: false
        noHotCopy:
          replicas: 1
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
        memoryOption: 500Mi
      te:
        replicas: 1
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
        memoryOption: 500Mi
      persistence:
        enabled: true
        size: 5Gi

---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n0.nano
spec:
  features:
  - name: minimal-resources
---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n0.small
spec:
  features:
  - name: minimal-resources
---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n1.small
spec:
  features:
  - name: minimal-resources
